### ISSUE TITLE
FastField Forms spreadsheet export - missing required sheets

### ISSUE THREAD

**Issue by jess-shue** [forestgeo/fgeo.tool#33]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/>, <https://community.rstudio.com/>, <https://github.com/forestgeo/forum/> or email Mauro Lepore at <maurolepore@gmail.com>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
When using FastField Forms for a re-census we've discovered or had submissions missing one or multiple of the required sheets:  'new_secondary_stems', 'recruits', and 'original_stems'. If no recruits are recorded in a quadrat, no sheet is exported. Likewise, post-submission if a recruit is found, then added to a 'new' file by itself, the  'new_secondary_stems', and 'original_stems' sheets are missing. This of course breaks the code and the files cannot be compiled. Any solution to this, or should I reach out to FastField Forms/add the sheets ourselves?
```r
> ######## Compile the separate worksheets from the quadrat workbooks into new excel files

> files.directory <- "C:/Users/shuej/Dropbox (Smithsonian)/Field_Form_Data_Entry/HF/uploads"

> files.export <- "C:/Users/shuej/Dropbox (Smithsonian)/Field_Form_Data_Entry/HF/exports/test"
> xl_sheets_to_xl(files.directory, files.export, first_census = FALSE)
Error: Data should contain these sheets:
original_stems, new_secondary_stems, recruits, root
* Missing sheets: recruits
In addition: Warning messages:
1: `new_secondary_stems` has cero rows. 
2: Filling every cero-row dataframe with NAs (new_secondary_stems). 
3: `new_secondary_stems` has cero rows. 
4: Filling every cero-row dataframe with NAs (new_secondary_stems). 
```

**Comment by maurolepore** [comment]
See [this email](https://mail.google.com/mail/u/0/?zx=yxdmg1oh1mf4#search/is%3Aunread+OR+has%3Ared-star+OR+has%3Ablue-star+OR+has%3Agreen-star/163e0c85fab1e4a4) for example file.

**Comment by maurolepore** [comment]
@jess-shue 

`xl_sheets_to_*()` now work with inputs missing key sheets. See the example below and notice the following:

1. A warning informs the missing sheets.
2. For each missing key sheet the output includes a row full of `NA`s, except for the column `sheet`. These rows are easy to remove with `is.na()` but I conservatively keep them to flag the key sheets the were missing from the input.

``` r
library(fgeo.tool)
input_dir <- dirname(example_path("missing_key/recensus.xlsx"))
xl_sheets_to_df(input_dir)
#> Warning: Adding missing sheets: original_stems, new_secondary_stems,
#> recruits, root.
#> $recensus.xlsx
#>                          submission_id  start_form_time_stamp
#> 1 199c553d-585b-4d2f-825a-cbd7e5c46550 2018.05.18 09:10:23 AM
#> 2                                 <NA>                   <NA>
#> 3                                 <NA>                   <NA>
#> 4                                 <NA>                   <NA>
#>      end_form_time_stamp               sheet section_id quadrat  tag
#> 1 2018.05.18 04:50:26 PM      form_meta_data       <NA>    <NA> <NA>
#> 2                   <NA>      original_stems       <NA>    <NA> <NA>
#> 3                   <NA> new_secondary_stems       <NA>    <NA> <NA>
#> 4                   <NA>            recruits       <NA>    <NA> <NA>
#>   stem_tag species   lx   ly  dbh status codes  pom dbh_2018 status_2018
#> 1     <NA>    <NA> <NA> <NA> <NA>   <NA>  <NA> <NA>     <NA>        <NA>
#> 2     <NA>    <NA> <NA> <NA> <NA>   <NA>  <NA> <NA>     <NA>        <NA>
#> 3     <NA>    <NA> <NA> <NA> <NA>   <NA>  <NA> <NA>     <NA>        <NA>
#> 4     <NA>    <NA> <NA> <NA> <NA>   <NA>  <NA> <NA>     <NA>        <NA>
#>   codes_2018 notes data_check dbh_check   px   py new_stem unique_stem
#> 1       <NA>  <NA>       <NA>      <NA> <NA> <NA>     <NA>       NA_NA
#> 2       <NA>  <NA>       <NA>      <NA> <NA> <NA>     <NA>       NA_NA
#> 3       <NA>  <NA>       <NA>      <NA> <NA> <NA>     <NA>       NA_NA
#> 4       <NA>  <NA>       <NA>      <NA> <NA> <NA>     <NA>       NA_NA
#>   date
#> 1 <NA>
#> 2 <NA>
#> 3 <NA>
#> 4 <NA>
```

Created on 2018-06-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
