### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/fgeo.tool#73]
You can read the documentation of the package __fgeo.tool__ [here](https://forestgeo.github.io/fgeo.tool). To suggest edits, please add your comments below or create a  new [pull request](https://github.com/forestgeo/fgeo.tool/pulls) ([see how](https://help.github.com/articles/about-pull-requests/)).

If you have any question, please ask me by referring to me as @maurolepore.

---
  
  Search related issues on <https://github.com> with: `label:hacktoberfest maurolepore`

![image](https://user-images.githubusercontent.com/5856545/47038227-eb4ac400-d14e-11e8-916a-4f002dd507cd.png)

**Comment by maurolepore** [comment]
@overstreeth, thank you very much for offering to review the documentation of packages that are approaching release. 

Could you please review [this help file](https://forestgeo.github.io/fgeo.tool/reference/fgeo_help.html)?

**Comment by overstreeth** [comment]
@maurolepore, how can I edit the intro text on R/imports-reexports-fgeo-base.R? (https://forestgeo.github.io/fgeo.tool/reference/pick_drop.html) 

Thank you!

**Comment by maurolepore** [comment]
Oh, here: https://github.com/forestgeo/fgeo.base/blob/master/R/pick_drop_var_cond.R

That helpfile is inherited from another package.

**Comment by overstreeth** [comment]
This worked, thanks! 

How can I edit the Arguments section of R/pick_top.R? The abbreviated conjunctions ("you've" and "that's") need to be full words. 

(https://forestgeo.github.io/fgeo.tool/reference/pick_top.html)

**Comment by maurolepore** [comment]
The arguments `.data` and `var` are inherited from the package __dplyr__. The author uses that style consistently across all his work so it's not worthwhile suggesting him to change it. Insted I copied-pasted the text and edited it as you suggested.

Thanks!
